In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [5]:
# Load the dataset required
car_accidents = pd.read_csv(r'C:\Users\wanji\OneDrive\Desktop\US Car Accident Machine Learning\archive (4)\US_Accidents_March23.csv')
car_accidents

## Performing EDA on the dataset

### Understanding the dataset
- Shape
- Column names, datatypes
- Statistics: std, mean, count

In [6]:
def dataset_info(dataset):

    dataset.info()

dataset_info(car_accidents)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7728394 entries, 0 to 7728393
Data columns (total 46 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ID                     object
 1   Source                 object
 2   Severity               int64
 3   Start_Time             object
 4   End_Time               object
 5   Start_Lat              float64
 6   Start_Lng              float64
 7   End_Lat                float64
 8   End_Lng                float64
 9   Distance(mi)           float64
 10  Description            object
 11  Street                 object
 12  City                   object
 13  County                 object
 14  State                  object
 15  Zipcode                object
 16  Country                object
 17  Timezone               object
 18  Airport_Code           object
 19  Weather_Timestamp      object
 20  Temperature(F)         float64
 21  Wind_Chill(F)          float64
 22  Humidity(%)            float64
 23  Pressure(in)           float64
 24  Visibility(mi)         float64
 25  Wind_Direction         object
 26  Wind_Speed(mph)        float64
 27  Precipitation(in)      float64
 28  Weather_Condition      object
 29  Amenity                bool
 30  Bump                   bool
 31  Crossing               bool
 32  Give_Way               bool
 33  Junction               bool
 34  No_Exit                bool
 35  Railway                bool
 36  Roundabout             bool
 37  Station                bool
 38  Stop                   bool
 39  Traffic_Calming        bool
 40  Traffic_Signal         bool
 41  Turning_Loop           bool
 42  Sunrise_Sunset         object
 43  Civil_Twilight         object
 44  Nautical_Twilight      object
 45  Astronomical_Twilight  object
dtypes: bool(13), float64(12), int64(1), object(20)
memory usage: 2.0+ GB

In [7]:
# Knowing the shape,columns,rows, column names and datatypes 
def get_dataset_shape(dataset):
    """
    Get the shape of the dataset

    Parameters:
    Pandas datafram

    Return 
    Tuple that shows the shape of the dataset 

    """

    shape = dataset.shape
    return shape

In [8]:
car_accident_shape = get_dataset_shape(car_accidents)
car_accident_shape

(7728394, 46)

In [9]:
# Column names and types 
def get_column_info(dataset):

    """
    Get columns and the data types for each

    """

    column_info = pd.DataFrame({'Column Name' : dataset.columns, 'Data Type': dataset.dtypes})
    return column_info

In [10]:
column_info_accidents = get_column_info(car_accidents)
print(column_info_accidents)

                                 Column Name Data Type
ID                                        ID    object
Source                                Source    object
Severity                            Severity     int64
Start_Time                        Start_Time    object
End_Time                            End_Time    object
Start_Lat                          Start_Lat   float64
Start_Lng                          Start_Lng   float64
End_Lat                              End_Lat   float64
End_Lng                              End_Lng   float64
Distance(mi)                    Distance(mi)   float64
Description                      Description    object
Street                                Street    object
City                                    City    object
County                                County    object
State                                  State    object
Zipcode                              Zipcode    object
Country                              Country    object
Timezone                            Timezone    object
Airport_Code                    Airport_Code    object
Weather_Timestamp          Weather_Timestamp    object
Temperature(F)                Temperature(F)   float64
Wind_Chill(F)                  Wind_Chill(F)   float64
Humidity(%)                      Humidity(%)   float64
Pressure(in)                    Pressure(in)   float64
Visibility(mi)                Visibility(mi)   float64
Wind_Direction                Wind_Direction    object
Wind_Speed(mph)              Wind_Speed(mph)   float64
Precipitation(in)          Precipitation(in)   float64
Weather_Condition          Weather_Condition    object
Amenity                              Amenity      bool
Bump                                    Bump      bool
Crossing                            Crossing      bool
Give_Way                            Give_Way      bool
Junction                            Junction      bool
No_Exit                              No_Exit      bool
Railway                              Railway      bool
Roundabout                        Roundabout      bool
Station                              Station      bool
Stop                                    Stop      bool
Traffic_Calming              Traffic_Calming      bool
Traffic_Signal                Traffic_Signal      bool
Turning_Loop                    Turning_Loop      bool
Sunrise_Sunset                Sunrise_Sunset    object
Civil_Twilight                Civil_Twilight    object
Nautical_Twilight          Nautical_Twilight    object
Astronomical_Twilight  Astronomical_Twilight    object

In [11]:
# Statistics 
def get_statistics(dataset):

    statistics_values = dataset.describe().transpose()
    return statistics_values

statistics_car_accidents = get_statistics(car_accidents)
statistics_car_accidents

,count,mean,std,min,25%,50%,75%,max
Severity,7728394.0,2.212384,0.487531,1.000000,2.000000,2.000000,2.000000,4.000000
Start_Lat,7728394.0,36.201195,5.076079,24.554800,33.399631,35.823974,40.084959,49.002201
Start_Lng,7728394.0,-94.702545,17.391756,-124.623833,-117.219396,-87.766616,-80.353676,-67.113167
End_Lat,4325632.0,36.261829,5.272905,24.566013,33.462070,36.183495,40.178920,49.075000
End_Lng,4325632.0,-95.725570,18.107928,-124.545748,-117.754345,-88.027890,-80.247086,-67.109242
Distance(mi),7728394.0,0.561842,1.776811,0.000000,0.000000,0.030000,0.464000,441.750000
Temperature(F),7564541.0,61.663286,19.013653,-89.000000,49.000000,64.000000,76.000000,207.000000
Wind_Chill(F),5729375.0,58.251048,22.389832,-89.000000,43.000000,62.000000,75.000000,207.000000
Humidity(%),7554250.0,64.831041,22.820968,1.000000,48.000000,67.000000,84.000000,100.000000
Pressure(in),7587715.0,29.538986,1.006190,0.000000,29.370000,29.860000,30.030000,58.630000
Visibility(mi),7551296.0,9.090376,2.688316,0.000000,10.000000,10.000000,10.000000,140.000000
Wind_Speed(mph),7157161.0,7.685490,5.424983,0.000000,4.600000,7.000000,10.400000,1087.000000
Precipitation(in),5524808.0,0.008407,0.110225,0.000000,0.000000,0.000000,0.000000,36.470000

## Data Cleaning

In [19]:
# Check for duplicates 
def get_duplicates(dataset):

    duplicate_values = dataset.duplicated()
    return duplicate_values

In [20]:
accident_duplicate_values = get_duplicates(car_accidents)
print(accident_duplicate_values)

0          False
1          False
2          False
3          False
4          False
           ...
7728389    False
7728390    False
7728391    False
7728392    False
7728393    False
Length: 7728394, dtype: bool

In [21]:
# Identify missing values 
def identify_missing_values(dataset):
    """
    Identify missing values in a dataset.
    
    Parameters:
    - dataset: Pandas DataFrame or Series
    
    Returns:
    - DataFrame with column names and the corresponding count of missing values
    """
    missing_values = dataset.isnull().sum().reset_index()
    missing_values.columns = ['Column Name', 'Missing Values']
    return missing_values

In [22]:
missing_values_accidents = identify_missing_values(car_accidents)
print(missing_values_accidents)

              Column Name  Missing Values
0                      ID               0
1                  Source               0
2                Severity               0
3              Start_Time               0
4                End_Time               0
5               Start_Lat               0
6               Start_Lng               0
7                 End_Lat         3402762
8                 End_Lng         3402762
9            Distance(mi)               0
10            Description               5
11                 Street           10869
12                   City             253
13                 County               0
14                  State               0
15                Zipcode            1915
16                Country               0
17               Timezone            7808
18           Airport_Code           22635
19      Weather_Timestamp          120228
20         Temperature(F)          163853
21          Wind_Chill(F)         1999019
22            Humidity(%)          174144
23           Pressure(in)          140679
24         Visibility(mi)          177098
25         Wind_Direction          175206
26        Wind_Speed(mph)          571233
27      Precipitation(in)         2203586
28      Weather_Condition          173459
29                Amenity               0
30                   Bump               0
31               Crossing               0
32               Give_Way               0
33               Junction               0
34                No_Exit               0
35                Railway               0
36             Roundabout               0
37                Station               0
38                   Stop               0
39        Traffic_Calming               0
40         Traffic_Signal               0
41           Turning_Loop               0
42         Sunrise_Sunset           23246
43         Civil_Twilight           23246
44      Nautical_Twilight           23246
45  Astronomical_Twilight           23246